### ISSUE TITLE
Recent tags are not shown

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#698] opened 2017-01-23 07:38 UTC
With more than 400 content in the ideascube media-center. After adding new content, new tags are not shown. 

How could we managed to show all tags ?

**Comment by bochecha** [comment] 2017-01-23 08:50
> new tags are not shown.

Not shown where?

**Comment by fheslouin** [comment] 2017-01-23 15:38
> Not shown where?

New tags are not shown in the media-center on the right menu (topic menu). It seems that there is a limit on tags shown, which can be a problem when people are adding new content with new tags

**Comment by bochecha** [comment] 2017-01-23 15:48
Indeed, there's a limit when displaying tags, set to 20 by default: https://github.com/ideascube/ideascube/blob/58dd55bc9f0139cbf710da0e55dcb0ef2ac87c48/ideascube/templatetags/ideascube_tags.py#L60-L70

I'm not sure we really want to always show all tags, the list could be pretty big, to the point of becoming almost useless, cramped in that small sidebar.

Maybe we could keep a limit by default, but add a link to a page displaying all tags?

**Comment by fheslouin** [comment] 2017-01-23 16:11
We have to think about it, because tags are more or less the only way to dig into the content media center. If they can not be shown then for sure some content will never be accessed. 
We can do two things
- Show last tags at first in the topic box
- Link to a page with all tags

**Comment by mgautierfr** [comment] 2017-01-23 17:09
How many tags have we ?
Maybe 20 is not enough but tags are to "regroup" content together. We should not have hundreds of tags.

It doesn't fix displaying of tags but we could add a entry with completion to allow user to filter on tags not displayed.

**Comment by bochecha** [comment] 2017-01-23 17:13
> It doesn't fix displaying of tags but we could add a entry with completion to allow user to filter on tags not displayed.

That would mean using Javascript.

The mediacenter is part of the public pages, where we agreed last week to try and limit the use of Javascript to the bare minimum.

**Comment by mgautierfr** [comment] 2017-01-23 17:18
arf.. you're right.
We have to find something else :/

**Comment by mgautierfr** [comment] 2017-02-01 10:25
Duplicate of #287

**Closed** 2017-04-14 07:52 UTC
Labels: media-center
